services:
  mongo:
    image: mongo:latest
    container_name: mongo-db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-network

  mongo-init:
    image: mongo:latest
    depends_on:
      - mongo
    restart: "no"
    volumes:
      - ./initReplica.sh:/initReplica.sh:ro
    entrypoint: ["sh", "/initReplica.sh"]
    networks:
      - backend-network

  redis:
    image: redis:8-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks: 
      - backend-network

  app-api:
    image: backend-image
    build: .
    command: sh -c "pnpm prisma db push && pnpm run start:api"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
      - mongo-init
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - backend-network

  app-scheduler:
    image: backend-image
    build: .
    command: npm run start:cron
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome
    depends_on:
      - redis
    networks:
      - backend-network

  app-worker:
    image: backend-image
    build: .
    command: npm run start:worker
    environment:
      - REDIS_HOST=redis
      - EMAIL_USER=${EMAIL_USER}
      - GOOGLE_APP_PASSWORD=${GOOGLE_APP_PASSWORD}
    depends_on:
      - redis
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
